/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'
import { Route as ReadyProjectIdRouteImport } from './routes/ready.$projectId'
import { Route as RfProjectIdIndexRouteImport } from './routes/rf.$projectId.index'
import { Route as RfProjectIdConfigRouteImport } from './routes/rf.$projectId.config'
import { Route as RfProjectIdOverviewRouteImport } from './routes/rf.$projectId.overview'
import { Route as RfProjectIdPrepareRouteImport } from './routes/rf.$projectId.prepare'
import { Route as RfProjectIdProfileRouteImport } from './routes/rf.$projectId.profile'
import { Route as RfProjectIdProfileReadyRouteImport } from './routes/rf.$projectId.profile-ready'
import { Route as RfProjectIdReadyRouteImport } from './routes/rf.$projectId.ready'
import { Route as RfProjectIdSimulateRouteImport } from './routes/rf.$projectId.simulate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyProjectIdRoute = ReadyProjectIdRouteImport.update({
  id: '/ready/$projectId',
  path: '/ready/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdIndexRoute = RfProjectIdIndexRouteImport.update({
  id: '/rf/$projectId/',
  path: '/rf/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdConfigRoute = RfProjectIdConfigRouteImport.update({
  id: '/rf/$projectId/config',
  path: '/rf/$projectId/config',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdOverviewRoute = RfProjectIdOverviewRouteImport.update({
  id: '/rf/$projectId/overview',
  path: '/rf/$projectId/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdPrepareRoute = RfProjectIdPrepareRouteImport.update({
  id: '/rf/$projectId/prepare',
  path: '/rf/$projectId/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdProfileRoute = RfProjectIdProfileRouteImport.update({
  id: '/rf/$projectId/profile',
  path: '/rf/$projectId/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdProfileReadyRoute = RfProjectIdProfileReadyRouteImport.update({
  id: '/rf/$projectId/profile-ready',
  path: '/rf/$projectId/profile-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdReadyRoute = RfProjectIdReadyRouteImport.update({
  id: '/rf/$projectId/ready',
  path: '/rf/$projectId/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdSimulateRoute = RfProjectIdSimulateRouteImport.update({
  id: '/rf/$projectId/simulate',
  path: '/rf/$projectId/simulate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/ready/$projectId': typeof ReadyProjectIdRoute
  '/rf/$projectId/config': typeof RfProjectIdConfigRoute
  '/rf/$projectId/overview': typeof RfProjectIdOverviewRoute
  '/rf/$projectId/prepare': typeof RfProjectIdPrepareRoute
  '/rf/$projectId/profile': typeof RfProjectIdProfileRoute
  '/rf/$projectId/profile-ready': typeof RfProjectIdProfileReadyRoute
  '/rf/$projectId/ready': typeof RfProjectIdReadyRoute
  '/rf/$projectId/simulate': typeof RfProjectIdSimulateRoute
  '/rf/$projectId/': typeof RfProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/ready/$projectId': typeof ReadyProjectIdRoute
  '/rf/$projectId/config': typeof RfProjectIdConfigRoute
  '/rf/$projectId/overview': typeof RfProjectIdOverviewRoute
  '/rf/$projectId/prepare': typeof RfProjectIdPrepareRoute
  '/rf/$projectId/profile': typeof RfProjectIdProfileRoute
  '/rf/$projectId/profile-ready': typeof RfProjectIdProfileReadyRoute
  '/rf/$projectId/ready': typeof RfProjectIdReadyRoute
  '/rf/$projectId/simulate': typeof RfProjectIdSimulateRoute
  '/rf/$projectId': typeof RfProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/ready/$projectId': typeof ReadyProjectIdRoute
  '/rf/$projectId/config': typeof RfProjectIdConfigRoute
  '/rf/$projectId/overview': typeof RfProjectIdOverviewRoute
  '/rf/$projectId/prepare': typeof RfProjectIdPrepareRoute
  '/rf/$projectId/profile': typeof RfProjectIdProfileRoute
  '/rf/$projectId/profile-ready': typeof RfProjectIdProfileReadyRoute
  '/rf/$projectId/ready': typeof RfProjectIdReadyRoute
  '/rf/$projectId/simulate': typeof RfProjectIdSimulateRoute
  '/rf/$projectId/': typeof RfProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
    | '/ready/$projectId'
    | '/rf/$projectId/config'
    | '/rf/$projectId/overview'
    | '/rf/$projectId/prepare'
    | '/rf/$projectId/profile'
    | '/rf/$projectId/profile-ready'
    | '/rf/$projectId/ready'
    | '/rf/$projectId/simulate'
    | '/rf/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
    | '/ready/$projectId'
    | '/rf/$projectId/config'
    | '/rf/$projectId/overview'
    | '/rf/$projectId/prepare'
    | '/rf/$projectId/profile'
    | '/rf/$projectId/profile-ready'
    | '/rf/$projectId/ready'
    | '/rf/$projectId/simulate'
    | '/rf/$projectId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
    | '/ready/$projectId'
    | '/rf/$projectId/config'
    | '/rf/$projectId/overview'
    | '/rf/$projectId/prepare'
    | '/rf/$projectId/profile'
    | '/rf/$projectId/profile-ready'
    | '/rf/$projectId/ready'
    | '/rf/$projectId/simulate'
    | '/rf/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
  ReadyProjectIdRoute: typeof ReadyProjectIdRoute
  RfProjectIdConfigRoute: typeof RfProjectIdConfigRoute
  RfProjectIdOverviewRoute: typeof RfProjectIdOverviewRoute
  RfProjectIdPrepareRoute: typeof RfProjectIdPrepareRoute
  RfProjectIdProfileRoute: typeof RfProjectIdProfileRoute
  RfProjectIdProfileReadyRoute: typeof RfProjectIdProfileReadyRoute
  RfProjectIdReadyRoute: typeof RfProjectIdReadyRoute
  RfProjectIdSimulateRoute: typeof RfProjectIdSimulateRoute
  RfProjectIdIndexRoute: typeof RfProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready/$projectId': {
      id: '/ready/$projectId'
      path: '/ready/$projectId'
      fullPath: '/ready/$projectId'
      preLoaderRoute: typeof ReadyProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/': {
      id: '/rf/$projectId/'
      path: '/rf/$projectId'
      fullPath: '/rf/$projectId/'
      preLoaderRoute: typeof RfProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/config': {
      id: '/rf/$projectId/config'
      path: '/rf/$projectId/config'
      fullPath: '/rf/$projectId/config'
      preLoaderRoute: typeof RfProjectIdConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/overview': {
      id: '/rf/$projectId/overview'
      path: '/rf/$projectId/overview'
      fullPath: '/rf/$projectId/overview'
      preLoaderRoute: typeof RfProjectIdOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/prepare': {
      id: '/rf/$projectId/prepare'
      path: '/rf/$projectId/prepare'
      fullPath: '/rf/$projectId/prepare'
      preLoaderRoute: typeof RfProjectIdPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/profile': {
      id: '/rf/$projectId/profile'
      path: '/rf/$projectId/profile'
      fullPath: '/rf/$projectId/profile'
      preLoaderRoute: typeof RfProjectIdProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/profile-ready': {
      id: '/rf/$projectId/profile-ready'
      path: '/rf/$projectId/profile-ready'
      fullPath: '/rf/$projectId/profile-ready'
      preLoaderRoute: typeof RfProjectIdProfileReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/ready': {
      id: '/rf/$projectId/ready'
      path: '/rf/$projectId/ready'
      fullPath: '/rf/$projectId/ready'
      preLoaderRoute: typeof RfProjectIdReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/simulate': {
      id: '/rf/$projectId/simulate'
      path: '/rf/$projectId/simulate'
      fullPath: '/rf/$projectId/simulate'
      preLoaderRoute: typeof RfProjectIdSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
  ReadyProjectIdRoute: ReadyProjectIdRoute,
  RfProjectIdConfigRoute: RfProjectIdConfigRoute,
  RfProjectIdOverviewRoute: RfProjectIdOverviewRoute,
  RfProjectIdPrepareRoute: RfProjectIdPrepareRoute,
  RfProjectIdProfileRoute: RfProjectIdProfileRoute,
  RfProjectIdProfileReadyRoute: RfProjectIdProfileReadyRoute,
  RfProjectIdReadyRoute: RfProjectIdReadyRoute,
  RfProjectIdSimulateRoute: RfProjectIdSimulateRoute,
  RfProjectIdIndexRoute: RfProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
