/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'
import { Route as ReadyProjectIdRouteImport } from './routes/ready.$projectId'
import { Route as RfProjectIdIndexRouteImport } from './routes/rf.$projectId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyProjectIdRoute = ReadyProjectIdRouteImport.update({
  id: '/ready/$projectId',
  path: '/ready/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const RfProjectIdIndexRoute = RfProjectIdIndexRouteImport.update({
  id: '/rf/$projectId/',
  path: '/rf/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/ready/$projectId': typeof ReadyProjectIdRoute
  '/rf/$projectId/': typeof RfProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/ready/$projectId': typeof ReadyProjectIdRoute
  '/rf/$projectId': typeof RfProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/ready/$projectId': typeof ReadyProjectIdRoute
  '/rf/$projectId/': typeof RfProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
    | '/ready/$projectId'
    | '/rf/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
    | '/ready/$projectId'
    | '/rf/$projectId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/projects'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
    | '/ready/$projectId'
    | '/rf/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
  ReadyProjectIdRoute: typeof ReadyProjectIdRoute
  RfProjectIdIndexRoute: typeof RfProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready/$projectId': {
      id: '/ready/$projectId'
      path: '/ready/$projectId'
      fullPath: '/ready/$projectId'
      preLoaderRoute: typeof ReadyProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/$projectId/': {
      id: '/rf/$projectId/'
      path: '/rf/$projectId'
      fullPath: '/rf/$projectId/'
      preLoaderRoute: typeof RfProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
  ReadyProjectIdRoute: ReadyProjectIdRoute,
  RfProjectIdIndexRoute: RfProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
